dependencies:
	python3 -m pip install pymongo 
	python3 -m pip install colorama
	npm install esprima
	npm install escodegen
	npm install -f -g n 
	mv node_modules/ package-lock.json package.json ..

submodule:
	cd ../test262/
	git submodule init
	git submodule update