dependencies:
	npm install -f -g n
	n 0.10.48
	n 6.17.1
	n 16
	python3 -m pip install tqdm
	npm install esprima
	npm install escodegen
	mv node_modules/ package-lock.json package.json ..

submodule:
	cd ../../resources/test262/
	git submodule init
	git submodule update
